var characters=[
    //前卫
    {
        name:"莉玛",
        imgpath:"../../static/character_icons/rima.png",
        isSelected:false,
        defaultStar:1
    },{
        name:"宫子",
        imgpath:"../../static/character_icons/miyako.png",
        isSelected:false,
        defaultStar:2
    },{
        name:"空花",
        imgpath:"../../static/character_icons/kuuka.png",
        isSelected:false,
        defaultStar:2
    },{
        name:"纯",
        imgpath:"../../static/character_icons/jyun.png",
        isSelected:false,
        defaultStar:3
    },{
        name:"香织",
        imgpath:"../../static/character_icons/kaori.png",
        isSelected:false,
        defaultStar:2
    },{
        name:"佩可莉姆",
        imgpath:"../../static/character_icons/pekorimu.png",
        isSelected:false,
        defaultStar:1
    },{
        name:"望",
        imgpath:"../../static/character_icons/nozomi.png",
        isSelected:false,
        defaultStar:3
    },{
        name:"真琴",
        imgpath:'../../static/character_icons/makoto.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"秋乃",
        imgpath:'../../static/character_icons/akino.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"未奏希",
        imgpath:'../../static/character_icons/misogi.png',
        isSelected:false,
        defaultStar:1
    },{
        name:"日和",
        imgpath:'../../static/character_icons/hiyori.png',
        isSelected:false,
        defaultStar:1
    },{
        name:"绫音",
        imgpath:'../../static/character_icons/ayane.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"珠希",
        imgpath:'../../static/character_icons/tamaki.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"惠理子",
        imgpath:'../../static/character_icons/eriko.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"胡桃",
        imgpath:'../../static/character_icons/kurumi.png',
        isSelected:false,
        defaultStar:1
    },{
        name:"姬塔",
        imgpath:'../../static/character_icons/jiita.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"怜",
        imgpath:'../../static/character_icons/lei.png',
        isSelected:false,
        defaultStar:1
    },{
        name:"静流",
        imgpath:'../../static/character_icons/shizuru.png',
        isSelected:false,
        defaultStar:3
    },
    
    
    //中卫
    {
        name:"美美",
        imgpath:'../../static/character_icons/mimi.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"忍",
        imgpath:'../../static/character_icons/shinobu.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"真阳",
        imgpath:'../../static/character_icons/mahiru.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"由加莉",
        imgpath:'../../static/character_icons/yukari.png',
        isSelected:false,
        defaultStar:1
    },{
        name:"莫妮卡",
        imgpath:'../../static/character_icons/monika.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"妮诺",
        imgpath:'../../static/character_icons/nino.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"美东",
        imgpath:'../../static/character_icons/mifuyu.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"伊莉亚",
        imgpath:'../../static/character_icons/yiriya.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"咲恋",
        imgpath:"../../static/character_icons/saren.png",
        isSelected:false,
        defaultStar:3
    },{
        name:"杏奈",
        imgpath:'../../static/character_icons/annna.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"可可萝",
        imgpath:'../../static/character_icons/kokkoro.png',
        isSelected:false,
        defaultStar:1
    },{
        name:"铃",
        imgpath:'../../static/character_icons/linn.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"深月",
        imgpath:'../../static/character_icons/mitsuki.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"茜里",
        imgpath:'../../static/character_icons/akari.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"依里",
        imgpath:'../../static/character_icons/yori.png',
        isSelected:false,
        defaultStar:2
    }
    

    //后卫
    ,{
        name:"亚里沙",
        imgpath:'../../static/character_icons/arisa.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"璃乃",
        imgpath:'../../static/character_icons/rino.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"铃奈",
        imgpath:'../../static/character_icons/suzuna.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"栞",
        imgpath:'../../static/character_icons/shiori.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"伊绪",
        imgpath:'../../static/character_icons/io.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"铃莓",
        imgpath:'../../static/character_icons/suzume.png',
        isSelected:false,
        defaultStar:1
    },{
        name:"美里",
        imgpath:'../../static/character_icons/misato.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"凯露",
        imgpath:'../../static/character_icons/kyaru.png',
        isSelected:false,
        defaultStar:1
    },{
        name:"初音",
        imgpath:'../../static/character_icons/hatsune.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"美咲",
        imgpath:'../../static/character_icons/misaki.png',
        isSelected:false,
        defaultStar:1
    },{
        name:"碧",
        imgpath:'../../static/character_icons/aoi.png',
        isSelected:false,
        defaultStar:1
    },{
        name:"千歌",
        imgpath:'../../static/character_icons/chika.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"真步",
        imgpath:'../../static/character_icons/maho.png',
        isSelected:false,
        defaultStar:3
    },{
        name:"优衣",
        imgpath:'../../static/character_icons/yui.png',
        isSelected:false,
        defaultStar:1
    },{
        name:"雪",
        imgpath:'../../static/character_icons/yuki.png',
        isSelected:false,
        defaultStar:2
    },{
        name:"镜华",
        imgpath:'../../static/character_icons/kyoka.png',
        isSelected:false,
        defaultStar:3
    }
]

module.exports=characters;